# Generated by Django 2.2.5 on 2021-07-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E2BlackApp', '0006_auto_20210724_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='electrical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='pet_care',
            field=models.BooleanField(default=False),
        ),
    ]
