# Generated by Django 2.2.5 on 2021-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E2BlackApp', '0007_auto_20210724_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='electrical',
            field=models.CharField(default='Text', max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='garden',
            field=models.CharField(default='Text', max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='pet_care',
            field=models.CharField(default='Text', max_length=255),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
